//
// Created by Dklishch on 10/15/2023.
//

#ifndef OSLAB1_STATUSCODES_H
#define OSLAB1_STATUSCODES_H

#define RESULT_STATUS_OK 0
#define RESULT_STATUS_SOFT_FAULT 1
#define RESULT_STATUS_HARD_FAULT 2
#define RESULT_STATUS_TIMEOUT 3

#define RESULT_FAILED_F 4
#define RESULT_FAILED_G 5
#define RESULT_FAILED_BOTH 6

#endif //OSLAB1_STATUSCODES_H
